language: python
os: linux
dist: focal
cache: pip
python:
  - "3.10"
install:
  - pip3 install homeassistant dbus_fast
before_script:
  - ln -s travis_secrets.yaml secrets.yaml
  - ln -s travis_service_account.json service_account.json
  - mkdir -p /tmp/video /tmp/photo /tmp/music
  - touch /tmp/dummy.crt
  - sed -e 's%usr/share/nas%tmp%g' -i configuration.yaml
  - sed -e 's%/home/homeassistant/homeassistant/.*%/tmp/dummy.crt%g' -i configuration.yaml
  - hass --version
script:
  - hass -c . --script check_config
