language: python
cache: pip
python:
  - "3.7"
install:
  - pip3 install homeassistant
before_script:
  - mv travis_secrets.yaml secrets.yaml
  - mv travis_service_account.json service_account.json
  - hass --version
script:
  - hass -c . --script check_config
