- id: '1570109229223'
  alias: Update device tracker
  trigger:
  - event: start
    platform: homeassistant
  - minutes: /5
    platform: time_pattern
  condition: []
  action:
  - service: shell_command.hassd_update
- id: '1571174383981'
  alias: Disable counter decrease
  description: Revert counter if decreased
  trigger:
  - entity_id:
    - sensor.counter_0
    - sensor.counter_1
    - sensor.counter_2
    platform: state
  condition:
  - condition: template
    value_template: '{{trigger.from_state.state > trigger.to_state.state}}'
  action:
  - service: rest_command.set_counter
    data_template:
      name: '{{trigger.from_state.attributes.name}}'
      value: '{{trigger.from_state.state}}'
- alias: update_tosr0x
  trigger:
  - platform: time_pattern
    minutes: /5
  - platform: homeassistant
    event: start
  action:
    service: zha.issue_zigbee_cluster_command
    data:
      ieee: 00:13:a2:00:41:a0:7e:1a
      endpoint_id: 232
      cluster_id: 17
      cluster_type: in
      command: 0
      command_type: server
      args: a[
  id: d4da33cf91214b9bac5eb89d40138f7c
- alias: update_tosr0x_switch
  trigger:
    platform: event
    event_type: zha_event
    event_data:
      device_ieee: 00:13:a2:00:41:a0:7e:1a
      command: receive_data
  condition:
    condition: template
    value_template: '{{ trigger.event.data.args | length == 1 }}'
  action:
  - service_template: '{% if trigger.event.data.args.encode(''latin1'').hex() | int(base=16)
      | bitwise_and(2**0) %} input_boolean.turn_on {% else %} input_boolean.turn_off
      {% endif %}

      '
    data:
      entity_id: input_boolean.tosr0x_1_state
  - service_template: '{% if trigger.event.data.args.encode(''latin1'').hex() | int(base=16)
      | bitwise_and(2**1) %} input_boolean.turn_on {% else %} input_boolean.turn_off
      {% endif %}

      '
    data:
      entity_id: input_boolean.tosr0x_2_state
  - service_template: '{% if trigger.event.data.args.encode(''latin1'').hex() | int(base=16)
      | bitwise_and(2**2) %} input_boolean.turn_on {% else %} input_boolean.turn_off
      {% endif %}

      '
    data:
      entity_id: input_boolean.tosr0x_3_state
  - service_template: '{% if trigger.event.data.args.encode(''latin1'').hex() | int(base=16)
      | bitwise_and(2**3) %} input_boolean.turn_on {% else %} input_boolean.turn_off
      {% endif %}

      '
    data:
      entity_id: input_boolean.tosr0x_4_state
  id: 1005e8c7b33a4bac8bc5a19134ab67d6
- alias: update_tosr0x_temp
  trigger:
    platform: event
    event_type: zha_event
    event_data:
      device_ieee: 00:13:a2:00:41:a0:7e:1a
      command: receive_data
  condition:
    condition: template
    value_template: '{{ trigger.event.data.args | length == 2 }}'
  action:
    service: input_number.set_value
    data_template:
      entity_id: input_number.tosr0x_temp
      value: '{% if trigger.event.data.args.encode(''latin1'').hex() | int(base=16)
        > 32767 %} {{ trigger.event.data.args.encode(''latin1'').hex() | int(base=16)
        / 16 - 4096 }} {% else %} {{ trigger.event.data.args.encode(''latin1'').hex()
        | int(base=16) / 16 }} {% endif %}

        '
  id: 3d1d3ac37181489c90b2866016bb74ff
- id: '1573979827206'
  alias: fan always on
  description: ''
  trigger:
  - entity_id: light.lumi_lumi_relay_c2acn01_2321e803_1
    platform: state
    to: 'off'
  - event: start
    platform: homeassistant
  condition: []
  action:
  - device_id: d69bbd276fbb41be9d7072e227a348ab
    domain: light
    entity_id: light.lumi_lumi_relay_c2acn01_2321e803_1
    type: turn_on
- id: '1573980062944'
  alias: Humidifier fan on
  description: ''
  trigger:
  - entity_id: switch.humidifier_pump
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      entity_id: switch.humidifier_fan
    service: switch.turn_on
- id: '1573980200984'
  alias: Humidifier fan off
  description: ''
  trigger:
  - entity_id: switch.humidifier_pump
    for:
      minutes: 5
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      entity_id: switch.humidifier_fan
    service: switch.turn_off
- id: '1573981070471'
  alias: Humidifier toggle
  description: ''
  trigger:
  - event_data:
      device_ieee: 00:15:8d:00:02:d4:40:bf
      command: single
    event_type: zha_event
    platform: event
  condition: []
  action:
  - data:
      entity_id: input_number.humidifier_pwm
    service: input_number.toggle
- id: '1574013273869'
  alias: Humidifier max run time
  description: ''
  trigger:
  - entity_id: switch.humidifier_pump
    for: 0:02:00
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      entity_id: switch.humidifier_pump
    service: switch.turn_off
- id: '1574013738564'
  alias: Turn Humidifier On
  description: ''
  trigger:
  - entity_id: switch.humidifier_pump
    for: 0:03:00
    platform: state
    to: 'off'
  condition:
    condition: state
    entity_id: input_boolean.humidifier_pwm
    state: 'on'
  action:
  - data:
      entity_id: switch.humidifier_pump
    service: switch.turn_on
- id: '1574013961689'
  alias: Enable Humidifier
  description: ''
  trigger:
  - platform: numeric_state
    below: '50'
    entity_id: sensor.lumi_lumi_weather_3bfcf003_1_1029
  condition: []
  action:
  - data:
      entity_id: input_boolean.humidifier_pwm
    service: input_boolean.turn_on
- id: '1574013961690'
  alias: Disable Humidifier
  description: ''
  trigger:
  - platform: numeric_state
    above: '50'
    entity_id: sensor.lumi_lumi_weather_3bfcf003_1_1029
  condition: []
  action:
  - data:
      entity_id: input_boolean.humidifier_pwm
    service: input_boolean.turn_off
- id: '1574205383149'
  alias: Set pump strength
  description: ''
  trigger:
  - entity_id: input_number.pump_strength
    platform: state
  condition: []
  action:
  - service: zha.issue_zigbee_cluster_command
    data_template:
      ieee: 00:13:a2:00:41:a0:7e:1a
      endpoint_id: 219
      cluster_id: 13
      cluster_type: in
      command: 0
      command_type: server
      args: '{{ trigger.to_state.state|int }}'
- id: '1574587123101'
  alias: Humidifier sleep time
  description: ''
  trigger:
  - at: '18:55:00'
    platform: time
  condition: []
  action:
  - data:
      entity_id: automation.enable_humidifier
    service: automation.turn_off
