- id: '1570109229223'
  alias: Update device tracker
  trigger:
  - platform: homeassistant
    event: start
  - platform: time_pattern
    minutes: /5
  condition: []
  action:
  - service: shell_command.hassd_update
  mode: single
- id: '1571174383981'
  alias: Disable counter decrease
  description: Revert counter if decreased
  trigger:
  - platform: state
    entity_id:
    - sensor.counter_0
    - sensor.counter_1
    - sensor.counter_2
  condition:
  - condition: template
    value_template: '{{trigger.from_state.state > trigger.to_state.state}}'
  action:
  - service: rest_command.set_counter
    data:
      name: '{{trigger.from_state.attributes.name}}'
      value: '{{trigger.from_state.state}}'
  mode: single
- id: d4da33cf91214b9bac5eb89d40138f7c
  alias: tosr0x_update
  trigger:
  - platform: time_pattern
    seconds: /30
  - platform: homeassistant
    event: start
  - platform: event
    event_type: zha_event
    event_data:
      command: receive_data
      device_ieee: 00:13:a2:00:41:a0:7e:1a
  variables:
    switches: '{% if trigger is defined and trigger.platform == "event" and trigger.event.event_type
      == "zha_event" and trigger.event.data.args | length == 1 -%} {{ trigger.event.data.args.encode(''latin1'').hex()
      | int(base=16) }} {%- elif trigger is defined and trigger.platform == "event"
      and trigger.event.event_type == "zha_event" and trigger.event.data.args | length
      == 3 -%} {{ trigger.event.data.args.encode(''latin1'').hex()[4:] | int(base=16)
      }} {%- endif %}'
    temp: '{% if trigger is defined and trigger.platform == "event" and trigger.event.event_type
      == "zha_event" and trigger.event.data.args | length == 2 -%} {{ trigger.event.data.args.encode(''latin1'').hex()
      | int(base=16) }} {%- elif trigger is defined and trigger.platform == "event"
      and trigger.event.event_type == "zha_event" and trigger.event.data.args | length
      == 3 -%} {{ trigger.event.data.args.encode(''latin1'').hex()[:4] | int(base=16)
      }} {%- endif %}'
  action:
  - choose:
    - conditions:
      - condition: template
        value_template: '{{ trigger is defined and trigger.platform == "event" and
          trigger.event.event_type == "zha_event"}}'
      sequence:
      - choose:
        - conditions:
          - condition: template
            value_template: '{{ trigger.event.data.args | length == 1 }}'
          sequence:
          - variables:
              switches: '{{ trigger.event.data.args.encode(''latin1'').hex() | int(base=16)
                }}'
        - conditions:
          - condition: template
            value_template: '{{ trigger.event.data.args | length == 2 }}'
          sequence:
          - variables:
              temp: '{{ trigger.event.data.args.encode(''latin1'').hex() | int(base=16)
                }}'
        - conditions:
          - condition: template
            value_template: '{{ trigger.event.data.args | length == 3 }}'
          sequence:
          - variables:
              temp: '{{ trigger.event.data.args.encode(''latin1'').hex()[:4] | int(base=16)
                }}'
              switches: '{{ trigger.event.data.args.encode(''latin1'').hex()[4:] |
                int(base=16) }}'
      - choose:
        - conditions:
          - condition: template
            value_template: '{{ switches is defined and switches is integer }}'
          sequence:
          - service: '{% if switches | bitwise_and(2**0) %} input_boolean.turn_on
              {% else %} input_boolean.turn_off {% endif %}'
            data:
              entity_id: input_boolean.tosr0x_1_state
          - service: '{% if switches | bitwise_and(2**1) %} input_boolean.turn_on
              {% else %} input_boolean.turn_off {% endif %}'
            data:
              entity_id: input_boolean.tosr0x_2_state
          - service: '{% if switches | bitwise_and(2**2) %} input_boolean.turn_on
              {% else %} input_boolean.turn_off {% endif %}'
            data:
              entity_id: input_boolean.tosr0x_3_state
          - service: '{% if switches | bitwise_and(2**3) %} input_boolean.turn_on
              {% else %} input_boolean.turn_off {% endif %}'
            data:
              entity_id: input_boolean.tosr0x_4_state
      - choose:
        - conditions:
          - condition: template
            value_template: '{{ temp is defined and temp is integer and temp != 65535
              }}'
          sequence:
          - service: input_number.set_value
            entity_id: input_number.tosr0x_temp
            data:
              value: '{% if temp > 32767 %} {{ temp / 16 - 4096 }} {% else %} {{ temp
                / 16 }} {% endif %}'
    default:
    - service: zha.issue_zigbee_cluster_command
      data:
        args: a[
        cluster_id: 17
        cluster_type: in
        command: 0
        command_type: server
        endpoint_id: 232
        ieee: 00:13:a2:00:41:a0:7e:1a
  mode: queued
  max: 10
- id: '1573979827206'
  alias: fan always on
  description: ''
  trigger:
  - platform: state
    entity_id: light.lumi_lumi_relay_fan
    to: 'off'
  - platform: homeassistant
    event: start
  condition: []
  action:
  - device_id: d69bbd276fbb41be9d7072e227a348ab
    domain: light
    entity_id: light.lumi_lumi_relay_fan
    type: turn_on
  mode: single
- id: '1573980062944'
  alias: Humidifier fan on
  description: Turn on fan when pump is active
  trigger:
  - platform: state
    entity_id: switch.humidifier_pump
    to: 'on'
  condition: []
  action:
  - service: switch.turn_on
    data:
      entity_id: switch.humidifier_fan
  mode: single
- id: '1573981070471'
  alias: Humidifier toggle
  description: Swich on and off on button press
  trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_ieee: 00:15:8d:00:02:d4:40:bf
      command: single
  condition: []
  action:
  - service: humidifier.toggle
    data: {}
    entity_id: humidifier.uvlazhnitel_v_detskoi,humidifier.uvlazhnitel_v_gostinoi,humidifier.uvlazhnitel_v_spalne
  mode: single
- id: pump_duty_cycle_off
  alias: Humidifier Duty Cycle Off
  description: ''
  trigger:
  - platform: state
    entity_id: switch.humidifier_pump
    for: 0:03:00
    to: 'on'
  - platform: state
    entity_id: group.humidifier_zones
    to: 'off'
  - platform: state
    entity_id: humidifier.uvlazhnitel_v_spalne,humidifier.uvlazhnitel_v_gostinoi,humidifier.uvlazhnitel_v_detskoi
    to: 'off'
  condition: []
  action:
  - service: homeassistant.turn_off
    entity_id: switch.humidifier_pump
    data: {}
  - delay: 00:00:03
  - service: homeassistant.turn_on
    entity_id: switch.tosr0x_4
    data: {}
  - delay: 00:00:15
  - service: homeassistant.turn_off
    entity_id: switch.tosr0x_1,switch.tosr0x_2,switch.tosr0x_3,switch.tosr0x_4
    data: {}
  mode: single
- id: pump_duty_cycle_on
  alias: Humidifier Duty Cycle On
  description: ''
  trigger:
  - platform: state
    entity_id: switch.humidifier_pump
    for: 0:06:00
    to: 'off'
  - platform: state
    entity_id: group.humidifier_zones
    to: 'on'
  - platform: event
    event_type: automation_reloaded
  condition:
  - condition: state
    entity_id: group.humidifier_zones
    state: 'on'
  action:
  - service: homeassistant.turn_off
    data: {}
    entity_id: switch.tosr0x_4
  - choose:
    - conditions:
      - condition: state
        entity_id: input_boolean.humidifier_zone_1
        state: 'on'
      sequence:
      - service: homeassistant.turn_on
        entity_id: switch.tosr0x_1
        data: {}
    default: []
  - choose:
    - conditions:
      - condition: state
        entity_id: input_boolean.humidifier_zone_2
        state: 'on'
      sequence:
      - service: homeassistant.turn_on
        entity_id: switch.tosr0x_2
        data: {}
    default: []
  - choose:
    - conditions:
      - condition: state
        entity_id: input_boolean.humidifier_zone_3
        state: 'on'
      sequence:
      - service: homeassistant.turn_on
        entity_id: switch.tosr0x_3
        data: {}
    default: []
  - choose:
    - conditions:
      - condition: state
        entity_id: group.tosr0x
        state: 'off'
      sequence:
      - wait_for_trigger:
        - platform: state
          entity_id: group.tosr0x
          to: 'on'
        timeout: ''
    default: []
  - service: homeassistant.turn_on
    entity_id: switch.humidifier_pump
    data: {}
  mode: single
- id: '1574205383149'
  alias: Set pump strength
  description: ''
  trigger:
  - platform: state
    entity_id: input_number.pump_strength
  condition: []
  action:
  - service: zha.set_zigbee_cluster_attribute
    data:
      ieee: 00:13:a2:00:41:a0:7e:1a
      endpoint_id: 219
      cluster_id: 13
      cluster_type: in
      attribute: 85
      value: '{{ trigger.to_state.state|int }}'
  mode: single
- id: '1574587123101'
  alias: Humidifier sleep time
  description: ''
  trigger:
  - platform: time
    at: '19:20:00'
  condition:
  - condition: state
    entity_id: humidifier.uvlazhnitel_v_detskoi,humidifier.uvlazhnitel_v_gostinoi,humidifier.uvlazhnitel_v_spalne
    state: 'on'
  action:
  - service: humidifier.turn_off
    data: {}
    entity_id: humidifier.uvlazhnitel_v_detskoi,humidifier.uvlazhnitel_v_gostinoi,humidifier.uvlazhnitel_v_spalne
  - service: input_number.set_value
    data:
      value: 320
    entity_id: input_number.pump_strength
  - service: homeassistant.update_entity
    data: {}
    entity_id: number.humidifier_pump_speed
  - delay: 0:45:00
  - service: humidifier.set_mode
    data:
      mode: away
    entity_id: humidifier.uvlazhnitel_v_gostinoi,humidifier.uvlazhnitel_v_spalne
  - service: humidifier.turn_on
    data: {}
    entity_id: humidifier.uvlazhnitel_v_gostinoi,humidifier.uvlazhnitel_v_spalne
  mode: single
- id: close_on_shutdown
  alias: Close on shutdown
  description: turn off everything when HA stops
  trigger:
  - platform: homeassistant
    event: shutdown
  action:
  - service: homeassistant.turn_off
    entity_id: switch.tosr0x_1, switch.tosr0x_2, switch.tosr0x_3, switch.tosr0x_4,
      switch.humidifier_pump, switch.humidifier_fan
    data: {}
  mode: single
- id: '1594502365341'
  alias: Ensure bathroom color temperature
  description: ''
  trigger:
  - device_id: ec863b8c8c384379a8185a51b3a8080c
    domain: light
    entity_id: light.hue_color_lamp_1
    platform: device
    type: turned_on
  - device_id: 6f2b7025f9ff4822b12db8c779420f00
    domain: light
    entity_id: light.hue_color_lamp_2
    platform: device
    type: turned_on
  - device_id: d69bbd276fbb41be9d7072e227a348ab
    domain: light
    entity_id: light.lumi_lumi_relay_fan
    platform: device
    type: turned_on
  condition: []
  action:
  - service: light.turn_on
    entity_id: light.hue_color_lamp_1,light.hue_color_lamp_2
    data:
      kelvin: 3500
  mode: single
- id: '1601500873265'
  alias: Water leak detected
  description: ''
  trigger:
  - type: turned_on
    platform: device
    device_id: 88c31869e37d42ef900a7d94964cd1eb
    entity_id: binary_sensor.lumi_lumi_sensor_wleak_aq1_035acf68_1_1280
    domain: binary_sensor
  condition: []
  action:
  - service: homeassistant.turn_off
    entity_id: humidifier.uvlazhnitel_zone_1,humidifier.uvlazhnitel_zone_2,humidifier.uvlazhnitel_zone_3
    data: {}
  - service: notify.mobile_app_sm_t725
    data:
      message: Water leak detected!
  mode: single
- id: '1602765181559'
  alias: Humidifier wake time
  description: ''
  trigger:
  - platform: time
    at: '10:00:00'
  condition:
  - condition: state
    entity_id: humidifier.uvlazhnitel_v_gostinoi,humidifier.uvlazhnitel_v_spalne
    state: 'on'
  action:
  - service: input_number.set_value
    data:
      value: 520
    entity_id: input_number.pump_strength
  - service: homeassistant.update_entity
    data: {}
    entity_id: number.humidifier_pump_speed
  - service: humidifier.set_mode
    data:
      mode: normal
    entity_id: humidifier.uvlazhnitel_v_gostinoi,humidifier.uvlazhnitel_v_spalne
  - service: humidifier.turn_on
    data: {}
    entity_id: humidifier.uvlazhnitel_v_detskoi
  mode: single
- id: '1604671440067'
  alias: Humidifier fan off
  description: ''
  trigger:
  - platform: state
    entity_id: humidifier.uvlazhnitel_v_spalne,humidifier.uvlazhnitel_v_detskoi,humidifier.uvlazhnitel_v_gostinoi
    to: 'off'
  condition:
  - condition: state
    entity_id: humidifier.uvlazhnitel_v_spalne,humidifier.uvlazhnitel_v_detskoi,humidifier.uvlazhnitel_v_gostinoi
    state: 'off'
  action:
  - type: turn_off
    device_id: d62ae9c5579f4bd682a506f6a7e00c2a
    entity_id: switch.humidifier_fan
    domain: switch
  mode: single
- id: '1606381449060'
  alias: Alisa volume down
  description: ''
  trigger:
  - platform: time
    at: '20:00'
  condition: []
  action:
  - service: media_player.volume_set
    data:
      volume_level: 0.2
    entity_id: media_player.yandex_station_ff98f0293c2e0ee4e18dc30d
  mode: single
- id: '1606381492447'
  alias: Alisa volume up
  description: ''
  trigger:
  - platform: time
    at: '10:00'
  condition: []
  action:
  - service: media_player.volume_set
    data:
      volume_level: 0.5
    entity_id: media_player.yandex_station_ff98f0293c2e0ee4e18dc30d
  mode: single
- id: '1606666024898'
  alias: Tag cebd1830-b810-41c6-818e-a97962bd9d1c is scanned
  description: ''
  trigger:
  - platform: tag
    tag_id: cebd1830-b810-41c6-818e-a97962bd9d1c
  condition: []
  action:
  - type: toggle
    device_id: ec863b8c8c384379a8185a51b3a8080c
    entity_id: light.hue_color_lamp_1
    domain: light
  - type: toggle
    device_id: 6f2b7025f9ff4822b12db8c779420f00
    entity_id: light.hue_color_lamp_2
    domain: light
  mode: single
