- id: '1570109229223'
  alias: Update device tracker
  trigger:
  - event: start
    platform: homeassistant
  - minutes: /5
    platform: time_pattern
  condition: []
  action:
  - service: shell_command.hassd_update
