- id: '1570109229223'
  alias: Update device tracker
  trigger:
  - platform: homeassistant
    event: start
  - platform: time_pattern
    minutes: /5
  condition: []
  action:
  - service: shell_command.hassd_update
  mode: single
- id: '1571174383981'
  alias: Disable counter decrease
  description: Revert counter if decreased
  trigger:
  - platform: state
    entity_id:
    - sensor.counter_0
    - sensor.counter_1
    - sensor.counter_2
  condition:
  - condition: template
    value_template: '{{trigger.from_state.state > trigger.to_state.state}}'
  action:
  - service: rest_command.set_counter
    data:
      name: '{{trigger.from_state.attributes.name}}'
      value: '{{trigger.from_state.state}}'
  mode: single
- id: d4da33cf91214b9bac5eb89d40138f7c
  alias: tosr0x_request
  trigger:
  - platform: time_pattern
    minutes: /5
  - platform: homeassistant
    event: start
  action:
  - service: zha.issue_zigbee_cluster_command
    data:
      args: a[
      cluster_id: 17
      cluster_type: in
      command: 0
      command_type: server
      endpoint_id: 232
      ieee: 00:13:a2:00:41:a0:7e:1a
  mode: queued
  max: 10
- id: 1005e8c7b33a4bac8bc5a19134ab67d6
  alias: tosr0x_response_switch
  trigger:
  - platform: event
    event_type: zha_event
    event_data:
      command: receive_data
      device_ieee: 00:13:a2:00:41:a0:7e:1a
  condition:
  - condition: template
    value_template: '{{ trigger.event.data.args | length == 1 }}'
  action:
  - service: '{% if trigger.event.data.args.encode(''latin1'').hex() | int(base=16)
      | bitwise_and(2**0) %} input_boolean.turn_on {% else %} input_boolean.turn_off
      {% endif %}'
    data:
      entity_id: input_boolean.tosr0x_1_state
  - service: '{% if trigger.event.data.args.encode(''latin1'').hex() | int(base=16)
      | bitwise_and(2**1) %} input_boolean.turn_on {% else %} input_boolean.turn_off
      {% endif %}'
    data:
      entity_id: input_boolean.tosr0x_2_state
  - service: '{% if trigger.event.data.args.encode(''latin1'').hex() | int(base=16)
      | bitwise_and(2**2) %} input_boolean.turn_on {% else %} input_boolean.turn_off
      {% endif %}'
    data:
      entity_id: input_boolean.tosr0x_3_state
  - service: '{% if trigger.event.data.args.encode(''latin1'').hex() | int(base=16)
      | bitwise_and(2**3) %} input_boolean.turn_on {% else %} input_boolean.turn_off
      {% endif %}'
    data:
      entity_id: input_boolean.tosr0x_4_state
  mode: queued
  max: 10
- id: 3d1d3ac37181489c90b2866016bb74ff
  alias: tosr0x_response_temp
  trigger:
  - platform: event
    event_type: zha_event
    event_data:
      command: receive_data
      device_ieee: 00:13:a2:00:41:a0:7e:1a
  condition:
  - condition: template
    value_template: '{{ trigger.event.data.args | length == 2 }}'
  action:
  - service: input_number.set_value
    data:
      value: '{% if trigger.event.data.args.encode(''latin1'').hex() | int(base=16)
        > 32767 %} {{ trigger.event.data.args.encode(''latin1'').hex() | int(base=16)
        / 16 - 4096 }} {% else %} {{ trigger.event.data.args.encode(''latin1'').hex()
        | int(base=16) / 16 }} {% endif %}'
    entity_id: input_number.tosr0x_temp
  mode: queued
  max: 10
- id: '1573979827206'
  alias: fan always on
  description: ''
  trigger:
  - platform: state
    entity_id: light.lumi_lumi_relay_fan
    to: 'off'
  - platform: homeassistant
    event: start
  condition: []
  action:
  - device_id: d69bbd276fbb41be9d7072e227a348ab
    domain: light
    entity_id: light.lumi_lumi_relay_fan
    type: turn_on
  mode: single
- id: '1573980062944'
  alias: Humidifier fan on
  description: Turn on fan when pump is active
  trigger:
  - platform: state
    entity_id: switch.humidifier_pump
    to: 'on'
  condition: []
  action:
  - service: switch.turn_on
    data:
      entity_id: switch.humidifier_fan
  mode: single
- id: '1573981070471'
  alias: Humidifier toggle
  description: Swich on and off on button press
  trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_ieee: 00:15:8d:00:02:d4:40:bf
      command: single
  condition: []
  action:
  - service: humidifier.toggle
    data: {}
    entity_id: humidifier.uvlazhnitel_zone_1, humidifier.uvlazhnitel_zone_2, humidifier.uvlazhnitel_zone_3
  mode: single
- id: pump_duty_cycle_off
  alias: Humidifier Pump Duty Cycle Off
  description: ''
  trigger:
  - platform: state
    entity_id: switch.humidifier_pump
    for: 0:03:00
    to: 'on'
  - platform: state
    entity_id: switch.humidifier_pump
    to: 'off'
  - platform: homeassistant
    event: start
  condition: []
  action:
  - service: homeassistant.turn_off
    entity_id: switch.humidifier_pump
    data: {}
  - delay: 00:00:02
  - service: switch.turn_on
    entity_id: switch.tosr0x_4
    data: {}
  - delay: 00:00:02
  - service: switch.turn_off
    entity_id: switch.tosr0x_1,switch.tosr0x_2,switch.tosr0x_3,switch.tosr0x_4
    data: {}
  mode: single
- id: pump_duty_cycle_on
  alias: Humidifier Pump Duty Cycle On
  description: ''
  trigger:
  - platform: state
    entity_id: switch.humidifier_pump
    for: 0:05:00
    to: 'off'
  condition:
  - condition: state
    entity_id: group.humidifier_zones
    state: 'on'
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: input_boolean.humidifier_zone_1
        state: 'on'
      sequence:
      - service: switch.turn_on
        entity_id: switch.tosr0x_1
        data: {}
    default: []
  - choose:
    - conditions:
      - condition: state
        entity_id: input_boolean.humidifier_zone_2
        state: 'on'
      sequence:
      - service: switch.turn_on
        entity_id: switch.tosr0x_2
        data: {}
    default: []
  - choose:
    - conditions:
      - condition: state
        entity_id: input_boolean.humidifier_zone_3
        state: 'on'
      sequence:
      - service: switch.turn_on
        entity_id: switch.tosr0x_3
        data: {}
    default: []
  - choose:
    - conditions:
      - condition: state
        entity_id: group.tosr0x
        state: 'off'
      sequence:
      - wait_for_trigger:
        - platform: state
          entity_id: group.tosr0x
          to: 'on'
        timeout: ''
    default: []
  - service: homeassistant.turn_on
    entity_id: switch.humidifier_pump
    data: {}
  mode: single
- id: '1574205383149'
  alias: Set pump strength
  description: ''
  trigger:
  - platform: state
    entity_id: input_number.pump_strength
  condition: []
  action:
  - service: zha.set_zigbee_cluster_attribute
    data:
      ieee: 00:13:a2:00:41:a0:7e:1a
      endpoint_id: 219
      cluster_id: 13
      cluster_type: in
      attribute: 85
      value: '{{ trigger.to_state.state|int }}'
  mode: single
- id: '1574587123101'
  alias: Humidifier sleep time
  description: ''
  trigger:
  - platform: time
    at: '18:55:00'
  condition: []
  action:
  - service: humidifier.turn_off
    data: {}
    entity_id: humidifier.uvlazhnitel_zone_1, humidifier.uvlazhnitel_zone_2, humidifier.uvlazhnitel_zone_3
  mode: single
- id: pump_control
  alias: Pump control
  description: Turn on pump when any of the zones start humidifying
  trigger:
  - platform: state
    entity_id: group.humidifier_zones
  - event: start
    platform: homeassistant
  condition: []
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: group.humidifier_zones
        state: 'on'
      sequence:
      - service: automation.trigger
        entity_id: automation.humidifier_pump_duty_cycle_on
        data: {}
    default:
    - service: automation.trigger
      entity_id: automation.humidifier_pump_duty_cycle_off
      data: {}
  mode: queued
  max: 10
- id: close_on_shutdown
  alias: Close on shutdown
  description: turn off everything when HA stops
  trigger:
  - platform: homeassistant
    event: shutdown
  action:
  - service: homeassistant.turn_off
    entity_id: switch.tosr0x_1, switch.tosr0x_2, switch.tosr0x_3, switch.tosr0x_4,
      switch.humidifier_pump, switch.humidifier_fan
    data: {}
  mode: single
- id: '1587844118867'
  alias: Cube Brightness
  description: ''
  trigger:
  - device_id: 3a6580cb094441b48c058d4168e3f021
    domain: zha
    platform: device
    subtype: left
    type: device_rotated
  - device_id: 3a6580cb094441b48c058d4168e3f021
    domain: zha
    platform: device
    subtype: right
    type: device_rotated
  condition: []
  action:
  - service: light.turn_on
    entity_id: light.children_room
    data:
      brightness_step: '{{[[trigger.event.data.args.relative_degrees | round | int,
        -255] | max, 255] | min}}'
  mode: single
- id: '1587847162438'
  alias: Cube Red
  description: ''
  trigger:
  - device_id: 3a6580cb094441b48c058d4168e3f021
    domain: zha
    platform: device
    subtype: face_1
    type: device_flipped
  condition: []
  action:
  - service: light.turn_on
    entity_id: light.children_room
    data:
      color_name: red
  mode: single
- id: '1587847941151'
  alias: Cube Green
  description: ''
  trigger:
  - device_id: 3a6580cb094441b48c058d4168e3f021
    domain: zha
    platform: device
    subtype: face_2
    type: device_flipped
  condition: []
  action:
  - service: light.turn_on
    entity_id: light.children_room
    data:
      color_name: green
- id: '1587848002690'
  alias: Cube Blue
  description: ''
  trigger:
  - device_id: 3a6580cb094441b48c058d4168e3f021
    domain: zha
    platform: device
    subtype: face_5
    type: device_flipped
  condition: []
  action:
  - service: light.turn_on
    entity_id: light.children_room
    data:
      color_name: blue
  mode: single
- id: '1587848113116'
  alias: Cube Yellow
  description: ''
  trigger:
  - device_id: 3a6580cb094441b48c058d4168e3f021
    domain: zha
    platform: device
    subtype: face_6
    type: device_flipped
  condition: []
  action:
  - service: light.turn_on
    entity_id: light.children_room
    data:
      color_name: yellow
  mode: single
- id: '1587848220263'
  alias: Cube BlueViolet
  description: ''
  trigger:
  - device_id: 3a6580cb094441b48c058d4168e3f021
    domain: zha
    platform: device
    subtype: face_3
    type: device_flipped
  condition: []
  action:
  - service: light.turn_on
    entity_id: light.children_room
    data:
      color_name: blueviolet
  mode: single
- id: '1587848685851'
  alias: Cube Magenta
  description: ''
  trigger:
  - device_id: 3a6580cb094441b48c058d4168e3f021
    domain: zha
    platform: device
    subtype: face_4
    type: device_flipped
  condition: []
  action:
  - service: light.turn_on
    entity_id: light.children_room
    data:
      color_name: magenta
- id: '1587848812070'
  alias: Cube Random
  description: ''
  trigger:
  - device_id: 3a6580cb094441b48c058d4168e3f021
    domain: zha
    platform: device
    subtype: turn_on
    type: device_shaken
  condition: []
  action:
  - service: light.turn_on
    entity_id: light.children_room
    data:
      effect: random
- id: '1587849275342'
  alias: Cube Default
  description: ''
  trigger:
  - device_id: 3a6580cb094441b48c058d4168e3f021
    domain: zha
    platform: device
    subtype: face_any
    type: device_knocked
  condition: []
  action:
  - service: light.turn_on
    entity_id: light.children_room
    data:
      kelvin: 3000
  mode: single
- id: '1587850084499'
  alias: Cube Drop
  description: ''
  trigger:
  - device_id: 3a6580cb094441b48c058d4168e3f021
    domain: zha
    platform: device
    subtype: turn_on
    type: device_dropped
  condition: []
  action:
  - service: light.turn_on
    entity_id:
    - light.hue_color_candle_1
    - light.hue_color_candle_2
    - light.hue_color_candle_3
    - light.hue_color_candle_4
    - light.hue_color_candle_5
    - light.hue_color_candle_6
    - light.hue_color_candle_7
    - light.hue_color_candle_8
    data:
      effect: random
      flash: short
  mode: single
- id: '1594502365341'
  alias: Ensure bathroom color temperature
  description: ''
  trigger:
  - device_id: ec863b8c8c384379a8185a51b3a8080c
    domain: light
    entity_id: light.hue_color_lamp_1
    platform: device
    type: turned_on
  - device_id: 6f2b7025f9ff4822b12db8c779420f00
    domain: light
    entity_id: light.hue_color_lamp_2
    platform: device
    type: turned_on
  - device_id: d69bbd276fbb41be9d7072e227a348ab
    domain: light
    entity_id: light.lumi_lumi_relay_fan
    platform: device
    type: turned_on
  condition: []
  action:
  - service: light.turn_on
    entity_id: light.hue_color_lamp_1,light.hue_color_lamp_2
    data:
      kelvin: 3500
  mode: single
- id: '1601500873265'
  alias: Water leak detected
  description: ''
  trigger:
  - type: turned_on
    platform: device
    device_id: 88c31869e37d42ef900a7d94964cd1eb
    entity_id: binary_sensor.lumi_lumi_sensor_wleak_aq1_035acf68_1_1280
    domain: binary_sensor
  condition: []
  action:
  - service: homeassistant.turn_off
    entity_id: humidifier.uvlazhnitel_zone_1,humidifier.uvlazhnitel_zone_2,humidifier.uvlazhnitel_zone_3
    data: {}
  - service: notify.mobile_app_sm_t725
    data:
      message: Water leak detected!
  mode: single
