
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

http:
  use_x_forwarded_for: true
  trusted_proxies: 127.0.0.1
  server_host: 127.0.0.1
  base_url: https://shulyaka.org.ru
  cors_allowed_origins: https://shulyaka.org.ru

recorder:
  db_url: mysql+pymysql://@/hass_db?unix_socket=/var/run/mysql/mysql.sock&charset=utf8

logger:
  default: debug

google_assistant:
  project_id: home-assistant-1404b
  api_key: !secret google_assistant

notify:
  - platform: html5
    name: html5
    vapid_pub_key: BA0ufUCAkPCSdEJBl2sStgZNOQicKJyEZnlTZvgPEOVG4HkJrafP7IcWHa-OSOON0EAAEUa9YoDqpPA-N3OCYVU
    vapid_prv_key: !secret web_push
    vapid_email: Shulyaka@gmail.com

zha:
  usb_path: /dev/ttyS1
  database_path: /srv/hass/zigbee.db
  radio_type: xbee
  baudrate: 9600

