name: Home Assistant CI
on:
  push:
  pull_request:
  schedule:
    - cron: 0 12 * * *

jobs:
  home-assistant:
    name: "Home Assistant Core ${{ matrix.version }} Configuration Check"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ["stable", "beta", "dev"]
    steps:
      - name: ⤵️ Check out configuration from GitHub
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - run: |
          ln -s ci_service_account.json service_account.json
          mkdir -p ./video ./photo ./music ./other/home-assistant-polymer-prod
          touch /tmp/dummy.crt
          sed -e 's%/usr/share/nas%.%g' -i configuration.yaml
          sed -e 's%/home/homeassistant/homeassistant/.*%/tmp/dummy.crt%g' -i configuration.yaml
      - name: 🚀 Run Home Assistant Configuration Check
        uses: frenck/action-home-assistant@v1
        with:
          path: "."
          secrets: ci_secrets.yaml
          version: "${{ matrix.version }}"
